name: Test Migration

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'connections'
        type: choice
        options:
          - connections
          - standard

jobs:
  test-connections-workflow:
    if: ${{ github.event.inputs.test_type == 'connections' }}
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/action.yml
    with:
      environment: staging
      service_name: test-connection-service
      header-value: "test-header-value"
      organization: occasio
      enable_ingress: true
      enable_status_cake: true
      replicas: "1"
      memory_limit: "512Mi"
      cpu_limit: "500m"
      is_connection_service: true
      monitor_name: "Test Monitor Staging"
      app_url: "https://staging.test-service.example.com"
      k8_ingress_url: "test-service-staging.example.internal"
      health_check_path: "/health"
    secrets:
      aws-github-oidc-iam-role: ${{ secrets.aws-github-oidc-iam-role }}
      slack_webhook_url: ${{ secrets.slack_webhook_url }}
      npm_token: ${{ secrets.npm_token }}
      tfc_token: ${{ secrets.tfc_token }}
      sentry_auth_token: ${{ secrets.sentry_auth_token }}
      github-token: ${{ secrets.TOKEN }}  # Use your new TOKEN secret
      service-api-key: ${{ secrets.service-api-key }}

  test-standard-workflow:
    if: ${{ github.event.inputs.test_type == 'standard' }}
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/action.yml
    with:
      environment: staging
      service_name: test-standard-service
      organization: occasio
      enable_ingress: true
      enable_status_cake: true
      replicas: "1"
      memory_limit: "512Mi"
      cpu_limit: "500m"
      is_connection_service: false
      monitor_name: "Test Standard Monitor Staging"
      app_url: "https://staging.standard-service.example.com"
      k8_ingress_url: "standard-service-staging.example.internal"
      health_check_path: "/health"
    secrets:
      aws-github-oidc-iam-role: ${{ secrets.aws-github-oidc-iam-role }}
      slack_webhook_url: ${{ secrets.slack_webhook_url }}
      npm_token: ${{ secrets.npm_token }}
      tfc_token: ${{ secrets.tfc_token }}
      sentry_auth_token: ${{ secrets.sentry_auth_token }}
      github-token: ${{ secrets.TOKEN }}  # Use your new TOKEN secret
